#!/bin/bash
#myapp              service of myapp
#
#description: Start stop restart status
#
#操作流程：
#1.chmod +x /path/my/service
#2.mv service /etc/init.d/myapp_service       #把该文件移到init.d目录下,要具有可执行权限.
#3.ls -sf /etc/init.d/myapp_service /etc/rc3.d/S100myapp_service


